services:
  # Container 1: The PostgreSQL Database
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: radan1386
      POSTGRES_DB: task_1_hamrah
    ports:
      - "5433:5432" # Optional: maps the DB to your Mac so you can inspect it via pgAdmin
    volumes:
      - pgdata:/var/lib/postgresql # Saves your data so it isn't lost when the container stops
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 20

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 10

  # Container 3: Event Logger Service
  logger:
    build:
      context: .
      dockerfile: logger.Dockerfile
    env_file:
      - .env
    ports:
      - "9090:9090"
    depends_on:
      postgres-db:
        condition: service_healthy

  # Container 4: Your Go Server
  grpc-server:
    build:
      context: .
      dockerfile: .Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080" # Maps the server to your Mac so the client can connect
    depends_on:
      postgres-db: # Ensures the database is actually accepting connections first
        condition: service_healthy
      redis:
        condition: service_healthy
      logger:
        condition: service_started

volumes:
  pgdata: # Defines the persistent volume for the database

