// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/Calculator.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_Calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_Calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_Calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type EventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReply) Reset() {
	*x = EventReply{}
	mi := &file_api_Calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReply) ProtoMessage() {}

func (x *EventReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_Calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReply.ProtoReflect.Descriptor instead.
func (*EventReply) Descriptor() ([]byte, []int) {
	return file_api_Calculator_proto_rawDescGZIP(), []int{1}
}

func (x *EventReply) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type CalcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num1          float64                `protobuf:"fixed64,2,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          float64                `protobuf:"fixed64,3,opt,name=num2,proto3" json:"num2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_api_Calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_Calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_api_Calculator_proto_rawDescGZIP(), []int{2}
}

func (x *CalcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CalcRequest) GetNum1() float64 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *CalcRequest) GetNum2() float64 {
	if x != nil {
		return x.Num2
	}
	return 0
}

func (x *CalcRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type CalcAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcAnswer) Reset() {
	*x = CalcAnswer{}
	mi := &file_api_Calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcAnswer) ProtoMessage() {}

func (x *CalcAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_Calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcAnswer.ProtoReflect.Descriptor instead.
func (*CalcAnswer) Descriptor() ([]byte, []int) {
	return file_api_Calculator_proto_rawDescGZIP(), []int{3}
}

func (x *CalcAnswer) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_api_Calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_Calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_api_Calculator_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReply) Reset() {
	*x = AuthReply{}
	mi := &file_api_Calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReply) ProtoMessage() {}

func (x *AuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_Calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReply.ProtoReflect.Descriptor instead.
func (*AuthReply) Descriptor() ([]byte, []int) {
	return file_api_Calculator_proto_rawDescGZIP(), []int{5}
}

func (x *AuthReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_Calculator_proto protoreflect.FileDescriptor

const file_api_Calculator_proto_rawDesc = "" +
	"\n" +
	"\x14api/Calculator.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x05Event\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"(\n" +
	"\n" +
	"EventReply\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"g\n" +
	"\vCalcRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04num1\x18\x02 \x01(\x01R\x04num1\x12\x12\n" +
	"\x04num2\x18\x03 \x01(\x01R\x04num2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\"$\n" +
	"\n" +
	"CalcAnswer\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"E\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\tAuthReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2~\n" +
	"\n" +
	"Calculator\x12#\n" +
	"\x04Calc\x12\f.CalcRequest\x1a\v.CalcAnswer\"\x00\x12&\n" +
	"\bRegister\x12\f.AuthRequest\x1a\n" +
	".AuthReply\"\x00\x12#\n" +
	"\x05Login\x12\f.AuthRequest\x1a\n" +
	".AuthReply\"\x0021\n" +
	"\x06Logger\x12'\n" +
	"\fStreamEvents\x12\x06.Event\x1a\v.EventReply\"\x00(\x01B\aZ\x05./apib\x06proto3"

var (
	file_api_Calculator_proto_rawDescOnce sync.Once
	file_api_Calculator_proto_rawDescData []byte
)

func file_api_Calculator_proto_rawDescGZIP() []byte {
	file_api_Calculator_proto_rawDescOnce.Do(func() {
		file_api_Calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_Calculator_proto_rawDesc), len(file_api_Calculator_proto_rawDesc)))
	})
	return file_api_Calculator_proto_rawDescData
}

var file_api_Calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_Calculator_proto_goTypes = []any{
	(*Event)(nil),                 // 0: Event
	(*EventReply)(nil),            // 1: EventReply
	(*CalcRequest)(nil),           // 2: CalcRequest
	(*CalcAnswer)(nil),            // 3: CalcAnswer
	(*AuthRequest)(nil),           // 4: AuthRequest
	(*AuthReply)(nil),             // 5: AuthReply
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_Calculator_proto_depIdxs = []int32{
	6, // 0: Event.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: Calculator.Calc:input_type -> CalcRequest
	4, // 2: Calculator.Register:input_type -> AuthRequest
	4, // 3: Calculator.Login:input_type -> AuthRequest
	0, // 4: Logger.StreamEvents:input_type -> Event
	3, // 5: Calculator.Calc:output_type -> CalcAnswer
	5, // 6: Calculator.Register:output_type -> AuthReply
	5, // 7: Calculator.Login:output_type -> AuthReply
	1, // 8: Logger.StreamEvents:output_type -> EventReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_Calculator_proto_init() }
func file_api_Calculator_proto_init() {
	if File_api_Calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_Calculator_proto_rawDesc), len(file_api_Calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_Calculator_proto_goTypes,
		DependencyIndexes: file_api_Calculator_proto_depIdxs,
		MessageInfos:      file_api_Calculator_proto_msgTypes,
	}.Build()
	File_api_Calculator_proto = out.File
	file_api_Calculator_proto_goTypes = nil
	file_api_Calculator_proto_depIdxs = nil
}
