// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/hello.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num1          float64                `protobuf:"fixed64,2,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          float64                `protobuf:"fixed64,3,opt,name=num2,proto3" json:"num2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_api_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{0}
}

func (x *CalcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CalcRequest) GetNum1() float64 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *CalcRequest) GetNum2() float64 {
	if x != nil {
		return x.Num2
	}
	return 0
}

func (x *CalcRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type CalcAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcAnswer) Reset() {
	*x = CalcAnswer{}
	mi := &file_api_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcAnswer) ProtoMessage() {}

func (x *CalcAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcAnswer.ProtoReflect.Descriptor instead.
func (*CalcAnswer) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{1}
}

func (x *CalcAnswer) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_api_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReply) Reset() {
	*x = AuthReply{}
	mi := &file_api_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReply) ProtoMessage() {}

func (x *AuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReply.ProtoReflect.Descriptor instead.
func (*AuthReply) Descriptor() ([]byte, []int) {
	return file_api_hello_proto_rawDescGZIP(), []int{3}
}

func (x *AuthReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_hello_proto protoreflect.FileDescriptor

const file_api_hello_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/hello.proto\"g\n" +
	"\vCalcRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04num1\x18\x02 \x01(\x01R\x04num1\x12\x12\n" +
	"\x04num2\x18\x03 \x01(\x01R\x04num2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\"$\n" +
	"\n" +
	"CalcAnswer\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"E\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\tAuthReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2~\n" +
	"\n" +
	"Calculator\x12#\n" +
	"\x04Calc\x12\f.CalcRequest\x1a\v.CalcAnswer\"\x00\x12&\n" +
	"\bRegister\x12\f.AuthRequest\x1a\n" +
	".AuthReply\"\x00\x12#\n" +
	"\x05Login\x12\f.AuthRequest\x1a\n" +
	".AuthReply\"\x00B\aZ\x05./apib\x06proto3"

var (
	file_api_hello_proto_rawDescOnce sync.Once
	file_api_hello_proto_rawDescData []byte
)

func file_api_hello_proto_rawDescGZIP() []byte {
	file_api_hello_proto_rawDescOnce.Do(func() {
		file_api_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_hello_proto_rawDesc), len(file_api_hello_proto_rawDesc)))
	})
	return file_api_hello_proto_rawDescData
}

var file_api_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_hello_proto_goTypes = []any{
	(*CalcRequest)(nil), // 0: CalcRequest
	(*CalcAnswer)(nil),  // 1: CalcAnswer
	(*AuthRequest)(nil), // 2: AuthRequest
	(*AuthReply)(nil),   // 3: AuthReply
}
var file_api_hello_proto_depIdxs = []int32{
	0, // 0: Calculator.Calc:input_type -> CalcRequest
	2, // 1: Calculator.Register:input_type -> AuthRequest
	2, // 2: Calculator.Login:input_type -> AuthRequest
	1, // 3: Calculator.Calc:output_type -> CalcAnswer
	3, // 4: Calculator.Register:output_type -> AuthReply
	3, // 5: Calculator.Login:output_type -> AuthReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_hello_proto_init() }
func file_api_hello_proto_init() {
	if File_api_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_hello_proto_rawDesc), len(file_api_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hello_proto_goTypes,
		DependencyIndexes: file_api_hello_proto_depIdxs,
		MessageInfos:      file_api_hello_proto_msgTypes,
	}.Build()
	File_api_hello_proto = out.File
	file_api_hello_proto_goTypes = nil
	file_api_hello_proto_depIdxs = nil
}
